apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zenith-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app.local  # Routes your main Flask web application
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 8000
  - host: db.local   # Routes your Mongo-Express dashboard safely
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 8081

